language: objective-c
before_install:
    - sudo easy_install cpp-coveralls
    - brew update
    - brew upgrade xctool

before_script:
    - cd ISO8601ForCocoa
script:
    - xcodebuild test -scheme 'ISO8601ForCocoa' SRCROOT=../build OBJROOT=../build SHARED_PRECOMPS_DIR=../build
    - xcodebuild test -scheme 'ISO8601ForCocoaTouch' -destination 'name=iPhone 6' SRCROOT=../build OBJROOT=../build SHARED_PRECOMPS_DIR=../build
after_success:
    - cd ..
    - coveralls -x '.m'
